### ISSUE TITLE
Is this project meant to be used in the real world or is it a political statement?

### ISSUE THREAD

**Issue by nsonnad** [offapi/rbac-23andme-oauth2#1]
Given the obvious ethical implications of this project, I must ask whether the goal of it is to:
1. Empower the minority communities you mention
2. Be a dystopian political statement
3. Be a technical demonstration of something highly offensive (as per your username, `offensive-computing`

**Comment by offensive-computing** [comment]
Why can't it be all three?

**Comment by nsonnad** [comment]
Fair enough
